name: Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish the app
      run: dotnet publish -c Release

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./src/bin/Release/net9.0/publish/ root@weatherappdemo.leansparkdigital.com:/var/www/myapp

    - name: Restart app (systemd example)
      run: ssh root 'sudo systemctl restart myapp.service'
